# Generated by Django 5.1.15 on 2026-04-20 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horário do Registro')),
                ('ip_registrado', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Registrado')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('negado', 'Negado'), ('pendente', 'Pendente')], default='pendente', max_length=10, verbose_name='Status')),
                ('motivo_negacao', models.TextField(blank=True, verbose_name='Motivo de Negação')),
                ('validado_rede', models.BooleanField(default=False, verbose_name='Rede Universitária Validada')),
                ('validado_geo', models.BooleanField(default=False, verbose_name='Geolocalização Validada')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenças', to='accounts.student', verbose_name='Aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenças', to='courses.aula', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'ordering': ['-horario_registro'],
                'unique_together': {('aluno', 'aula')},
            },
        ),
    ]
