# Generated by Django 5.1.15 on 2026-04-20 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Sala')),
                ('predio', models.CharField(max_length=100, verbose_name='Prédio')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
                ('raio_permitido', models.PositiveIntegerField(default=50, verbose_name='Raio Permitido (metros)')),
                ('capacidade', models.PositiveIntegerField(default=40, verbose_name='Capacidade')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['predio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('semestre', models.CharField(choices=[('1', '1º Semestre'), ('2', '2º Semestre'), ('3', '3º Semestre'), ('4', '4º Semestre'), ('5', '5º Semestre'), ('6', '6º Semestre'), ('7', '7º Semestre'), ('8', '8º Semestre'), ('9', '9º Semestre'), ('10', '10º Semestre')], max_length=2, verbose_name='Semestre')),
                ('ano', models.PositiveIntegerField(default=2024, verbose_name='Ano')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='accounts.professor', verbose_name='Professor Responsável')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Fim')),
                ('token_qrcode', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token QR Code')),
                ('qrcode_imagem', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='Imagem QR Code')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='courses.disciplina', verbose_name='Disciplina')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='courses.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['-data', '-horario_inicio'],
            },
        ),
    ]
