# Generated by Django 5.1.15 on 2026-05-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='aula',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='aula',
            name='raio_permitido',
            field=models.PositiveIntegerField(default=50, verbose_name='Raio Permitido (metros)'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30, verbose_name='Longitude'),
        ),
    ]
