# Generated by Django 5.1.15 on 2026-05-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0002_add_geo_fields_to_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='disciplinas', to='accounts.student', verbose_name='Alunos Matriculados'),
        ),
    ]
