# Generated by Django 5.1.15 on 2026-05-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_alunos_to_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Longitude'),
        ),
    ]
